name: tesis_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

# --- AQUÍ ESTÁ LA SECCIÓN DE DEPENDENCIAS UNIFICADA ---
dependencies:
  flutter:
    sdk: flutter

  # Librería para localización (Español)
  flutter_localizations:
    sdk: flutter

  # Tus otras librerías
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  intl: 0.20.2
# -----------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg